spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
